### ISSUE TITLE
Make CRUD method signatures compatible with Spring CrudRepository

### ISSUE THREAD

**Issue by ngonzalezpazFC** [FlowingCode/backend-core#43]
In order to support JPA derived query methods in projects with commons-backend, Javier proposed a solution that could not be achieved due some method signatures from commons-backend that differ to some Spring implementations.
A solution to this problem could be to make commons-backend method signatures compatible with Spring Data method signatures.

**Comment by javier-godoy** [comment]
For the record, the solution I proposed was for integrating `JpaDaoSupport` with spring data `Repository`\*, not with `CrudRepository`. There is no signature incompatibility because `Repository` is a marker interface. (Your point, however, still stands.)
```
interface PersonRepositoryCustom extends JpaDaoSupport<Person,Integer>;
interface PersonRepository extends Repository<Person, Long>, PersonRepositoryCustom;
class PersonRepositoryCustomImpl implements PersonRepositoryCustom;
```
(\*assuming an architecture with contracts and implementations in the same module)

`CrudRepository` offers an ample API for generic CRUD operations, while `JpaDaoSupport` offers a more limited API on the same lines, plus two criteria-like methods `filter` and `count`. Most of the API from `CrudRepository` is either absent from `JpaDaoSupport` or the signature is an exact match, except for `save` and `findAll`:

||SpringData (CrudRepository<T, ID>)| JpaDaoSupport<T,K> |
|---|---|---|
|❌|`<S extends T> S save(S entity)`| `K save(T entity)` and `void update(T entity)`|
||`<S extends T> Iterable<S> saveAll(Iterable<S> entities);`|
|✔|`Optional<T> findById(ID id)`| `Optional<T> findById(K id)`|
||`boolean existsById(ID id)`|
|❌|`Iterable<T> findAll()`|`List<T> findAll()`|
||`Iterable<T> findAllById(Iterable<ID> ids)`|
||`long count()`|
||`void deleteById(ID id)`|
|✔|`void delete(T entity)`| 	`void delete(T entity);`|
||`void deleteAllById(Iterable<? extends ID> ids)`|
||`void deleteAll(Iterable<? extends T> entities)`|
||`void deleteAll()`|
|||`List<T> filter(QuerySpec filter);`|
|||`long count(QuerySpec filter);`|	
	
Regarding signature compatibility, the case of `findAll()` is simpler because `List` implements `Iterable`, therefore the followng compiles:
```
public interface PersonRepository extends CrudRepository<Person, Long>, PersonRepositoryCustom  {
	@Override
	default List<Person> findAll() {
		return PersonRepositoryCustom.super.findAll();
	}
}
```

The case of `save` is problematic, not onty because of the signature (we cannot implement `<S extends T> S save(S entity)` in `ConversionJpaDaoSupport`) but also because `JpaDaoSupport` distinguished save from update, while `CrudRepository` doesn't. 

However, why would one prefer `JpaDaoSupport` over `CrudRepository` if both are available?
Instead, one could have 
```
interface PersonRepositoryCustom extends QueryDao<Person,Integer>;
interface PersonRepository extends CrudRepository<Person, Integer>, PersonRepositoryCustom;
class PersonRepositoryCustomImpl implements PersonRepositoryCustom, JpaDaoSupport<Person, Integer>;
```

**Comment by mlopezFC** [comment]
We had an internal discussion about this, here are some conclusions:
* The first approach mentioned by Javier works well (using Spring Data Repositories with `JpaDaoSupport`). The good thing with this approach is that you can use commons-backend stack along with spring data dynamically generated methods.
* We could provide in the future a `SpringDataDaoSupport` that could delegate crud calls to `CrudRepository` if it's needed (not a high priority right now, but it should be possible to do it)

**Comment by mlopezFC** [comment]
Closing this old ticket because it won't be implemented for now.
